services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dvdrental

    ports:
      - "5555:5432"
    volumes:
      - ./db/restore.sql:/docker-entrypoint-initdb.d/restore.sql
      - ./db/:/db/
